service: s3-lambda

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::bucket-tarea4-697830474638/*"

functions:
  s3Lambda:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: bucket-tarea4-697830474638
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
          existing: true

resources:
  Resources:
    S3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: bucket-tarea4-697830474638
